### ISSUE TITLE
(Question) Sonoma support?

### ISSUE THREAD

**Issue by biertester** [Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh-ventura#10]
Hey! Are you gonna update your EFI to support Sonoma? 👀 Coz for now with the beta 1 theyre still kaby lake graphics you can spoof, itlwm works with heliport ect, could be fun!

**Comment by Lost-Entrepreneur439** [comment]
While I will try, chances are unlikely. My 840 G3's screen circuitry seems to be damaged (even with a VGA monitor it's stuck at 800x600 and the internal screen isn't working at all) and that makes it quite difficult to update this EFI to work on Sonoma.
