### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by InfernoNova9999** [Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh-ventura#12]
First of all, thank you for making this, i used this for my first hackintosh and it saved me a lot of time. here are the issues i have:
Bluetooth isnt working. it just keeps spinning
keyboard shortcuts arent working such as volume and brightness
i have a 6200u model and it shows that i have an hd 620 with 1536 vram despite it being an 520 and having 4gb.

also this is not an issue but the default colorspace is really bad i suggest everyone to change it to Rec. ITU-R BT.709-5

**Comment by Lost-Entrepreneur439** [comment]
Bluetooth is a known issue on 13.4. Downgrade to 13.3.1a. 
Don't hold the function keys when controlling volume/brightness, just press the F keys. 
It's supposed to say HD 620 with 1.5gb. 1.5gb is just the default VRAM amount in macOS (it's unrelated to what it's set to in the BIOS) and the GPU needs to be spoofed to the 620 to use Ventura.

**Comment by Lost-Entrepreneur439** [comment]
first and second issue fixed in v1.2.1, third issue is normal behaviour
