### ISSUE TITLE
no updates showing

### ISSUE THREAD

**Issue by bouyhy1989** [Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh-ventura#14]
hello 
im on 13.6 but when selecting sonoma public or dev betas it keeps saying that 13.6 is the latest version up to date

**Comment by Lost-Entrepreneur439** [comment]
This is because the SMBIOS is not compatible with Sonoma.

**Comment by bouyhy1989** [comment]
Thank you for your reply , can you make it compatible and how i can get apple tv to work plz? Im really a noob on macos and hackintosh stuff

**Comment by Lost-Entrepreneur439** [comment]
Sonoma is not out yet, I will not provide any official support for it until it releases. As of right now, I only support Sonoma.

I don't use Apple TV so I don't know how to get it to work.
