### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mohitbagur** [Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh-ventura#21]
I'm trying to install on an identical configuration to OP's, except I'm running a 2.5 inch SATA SSD that is picked up fine by the installer. However, once the installation completes, the laptop displays a BootDevice Not Found error, and I'm not able to actually boot into the macOS install. On the next time I try and install it, there is definitely disk usage in the drive, which means _something_ did copy-- however, it still is not detected. I have formatted the drive as macOS Extended Journaled as well as APFS with GUID partition maps, but to no avail. Help!

**Comment by Lost-Entrepreneur439** [comment]
OpenCore does not automatically copy to your SSD. You need to boot your SSD via OpenCore.
