### ISSUE TITLE
Wifi not available on recovery mode in Ventura

### ISSUE THREAD

**Issue by nyxxxia** [Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh-ventura#23]
So, I've followed the entire process. I didn't touch the files, but, still, the wifi isn't available on recovery mode. Ifconfig recognizes the card (along other interfaces), but not anything else. I tried plugging in Ethernet, nothing.

**Comment by nyxxxia** [comment]
![Uploading 17176078583314587089304345772345.jpg…]()

**Comment by nyxxxia** [comment]
fixed by changing itlwm to airportitlwm

**Comment by Lost-Entrepreneur439** [comment]
> fixed by changing itlwm to airportitlwm

You are using the Sonoma EFI. The Ventura EFI uses airportitlwm. Switch EFIs.
