### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by MezzLasha** [Lost-Entrepreneur439/hp-elitebook-840-g3-hackintosh-ventura#5]
Hello, thanks for the great work for this device. Everything seems to work for me, except audio. I'm running Ventura downloaded from olarila, with your EFI. Is there a known fix for this problem? I'm also running an i5 840 g3.

**Comment by Lost-Entrepreneur439** [comment]
Will not be assisting with Olarila. Get macOS from macrecovery in OpenCorePkg.

**Comment by MezzLasha** [comment]
thanks, will try.
